# Generated by Django 4.0.3 on 2022-05-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='diferencaDeGolos',
        ),
    ]
