# Generated by Django 4.0.3 on 2022-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0002_remove_clube_diferencadegolos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='diferencaDeGolos',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
