# Generated by Django 4.0.3 on 2022-05-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0004_alter_liga_listaequipas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='diferencaDeGolos',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='empates',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='golosMarcados',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='golosSofridos',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='jogosDisputados',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='vitorias',
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogosDisputados', models.IntegerField(default=0, editable=False)),
                ('vitorias', models.IntegerField(default=0, editable=False)),
                ('empates', models.IntegerField(default=0, editable=False)),
                ('derrotas', models.IntegerField(default=0, editable=False)),
                ('golosMarcados', models.IntegerField(default=0, editable=False)),
                ('golosSofridos', models.IntegerField(default=0, editable=False)),
                ('diferencaDeGolos', models.IntegerField(default=0, editable=False)),
                ('pontos', models.IntegerField(default=0, editable=False)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clube', to='leagueTables.clube')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliga', to='leagueTables.liga')),
            ],
        ),
    ]
